name: Tag with Chromium version

on:
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  add_tag:
    runs-on: ubuntu-latest
    steps:
    - name: Get Chromium branch
      id: chromium
      shell: bash
      run: echo "::set-output name=branch::$(git ls-remote --heads https://pdfium.googlesource.com/pdfium.git | grep -ohP 'chromium/\d+' | tail -n1)"
    - name: Add tag
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: ${{ steps.chromium.outputs.branch }}